spring:
  datasource:
    # Defaults = docker-compose.yml. Se pueden pisar con variables de entorno
    url: ${DB_URL:jdbc:postgresql://localhost:5433/turnos}
    username: ${DB_USERNAME:turnos}
    password: ${DB_PASSWORD:turnos}
  jpa:
    show-sql: true
